name: Java CI
on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'adopt'
        - name: Create application.properties file
          run: |
            cd src/main/resources
            touch application.properties
            echo spring.datasource.url= jdbc:mysql://localhost:3306/login_info >> application.properties
            echo spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver >> application.properties
            echo spring.datasource.username= root >> application.properties
            echo spring.datasource.password= 1234 >> application.properties
            ls
            cd ..
            cd ..
            cd ..
        - name: Build with Gradle
          run: ./gradlew build -x test
        - uses: actions/upload-artifact@v3
          with:
            name: Package
            path: build/libs



